# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
name: nteract-landing
description: Take your computing experience to the next level.
url: nteract.github.io

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: dist
exclude: ['assets']

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 10

# Permalink structure and pagination options
permalink:
paginate: 10
paginate_path: 'page:num'
excerpt_separator: '<!--more-->'

# Markdown library and options
markdown: redcarpet
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart',
              'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']
highlighter: true

# Extending Jekyll
gems:
  - jekyll-archives
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
